name: Release

on:
  release:
    types:
      - published

concurrency:
  group: release-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build wheel and source distribution
        run: |
          pipx install build
          pipx run build

      - name: Upload wheel and source distribution to release
        run: |
          gh release upload ${{ github.ref_name }} ./dist/*.tar.gz  ./dist/*.whl --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
